spring:
  application:
    name: turbine

server:
  port: 8704

eureka:
  client:
    #注册中心的地址
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/


management:
  port: 8705

#聚合监控
turbine:
  #指定需要收集监控信息的服务名
  app-config: feign
  clusterNameExpression: new String("default")
  combine-host: true
#  aggregator:
#    clusterConfig: default
#  instanceUrlSuffix:
#    default: actuator/hystrix.stream
