spring:
  application:
    name: gateway
  cloud:
    gateway:
      #过滤工厂
#      default-filters:
#        - Auth=true

#      routes:
#        - id: feign
#          uri: lb://FEIGN
#          order: 0
#          predicates:
#            - Path=/feign/**
#          #StripPrefix一个非负整数，用是去掉前缀的，那个整数即对应层数 访问 /feign/feign/index，
#          #那么当网关服务向后转发请求时，会去掉/customer，微服务收到的就是/feign/index
#          filters:
#            - StripPrefix=1
#            - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      #是否与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为false，
      #设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #服务名小写
server:
  port: 8703
  address: 192.168.20.30

eureka:
  client:
    #注册中心的地址
    serviceUrl:
      defaultZone: http://192.168.20.30:8700/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${server.address}:${server.port}

logging:
  level:
    org.springframework.cloud.gateway: debug
