spring:
  application:
    name: gateway
  cloud:
    gateway:
#      routes:
#        id: feign
#        uri: lb://FEIGN
#        order: 0
#        predicates:
#          - Path: /feign/**
#        filters:
#          - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      #是否与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为false，
      #设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #服务名小写
server:
  port: 8703

eureka:
  client:
    #注册中心的地址
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug
