spring:
  application:
    name: feign

server:
  port: 8702

eureka:
  client:
    #注册中心的地址
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/

#开启断路器
feign:
  hystrix:
    enabled: true

  #client:
  #  config:
  #    feignName:
        #connectTimeout: 5000  # 相当于Request.Optionsn 连接超时时间
        #readTimeout: 5000     # 相当于Request.Options 读取超时时间
        #loggerLevel: full     # 配置Feign的日志级别，相当于代码配置方式中的Logger
        #errorDecoder: com.example.SimpleErrorDecoder  # Feign的错误解码器，相当于代码配置方式中的ErrorDecoder
        #retryer: com.example.SimpleRetryer  # 配置重试，相当于代码配置方式中的Retryer
        #requestInterceptors: # 配置拦截器，相当于代码配置方式中的RequestInterceptor
        #decode404: false  # 是否对404错误解码
        #encode: com.example.SimpleEncoder
        #decoder: com.example.SimpleDecoder
        #contract: com.example.SimpleContract
logging:
  level:
    #feign 日志以那个级别 监听那个接口
    com.cloud.feign.feignService: debug
  file:
    path: G:\0-0\

#断路监控仪表盘
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
